version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    versioning-strategy: lockfile-only
    schedule:
      interval: "monthly"
    reviewers:
      - ""
  - package-ecosystem: "bundler"
  directory: "/"
  versioning-strategy: lockfile-only
  schedule:
    interval: "monthly"
  reviewers:
    - ""
